**Feature Scaling**

In [400]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [401]:
df= pd.read_csv(r'F:\IT Learning\MY PROJECTS\Python Projects\Data Cleaning Datasets\titanic_data.csv')

In [402]:
df.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked classe  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [403]:
data= df[['survived','pclass','age','parch']]

In [404]:

data=pd.DataFrame(data)

In [405]:
imputer= SimpleImputer(missing_values= np.nan,strategy= 'mean')

In [406]:
data= imputer.fit_transform(df[['survived','pclass','age','parch']])

In [407]:
data= pd.DataFrame(data, columns= ['survived','pclass','age','parch'], dtype= 'int64' )

C:\Users\shory\AppData\Local\Temp\ipykernel_9028\1461317873.py:1: FutureWarning: In a future version, passing float-dtype values and an integer dtype to DataFrame will retain floating dtype if they cannot be cast losslessly (matching Series behavior). To retain the old behavior, use DataFrame(data).astype(dtype)
  data= pd.DataFrame(data, columns= ['survived','pclass','age','parch'], dtype= 'int64' )


In [408]:
data

survived  pclass  age  parch
0           0       3   22      0
1           1       1   38      0
2           1       3   26      0
3           1       1   35      0
4           0       3   35      0
..        ...     ...  ...    ...
884         0       2   27      0
885         1       1   19      0
886         0       3   29      2
887         1       1   26      0
888         0       3   32      0

[889 rows x 4 columns]

In [409]:
X= data.drop("survived", axis= 1)
y= data['survived']

In [410]:
X


pclass  age  parch
0         3   22      0
1         1   38      0
2         3   26      0
3         1   35      0
4         3   35      0
..      ...  ...    ...
884       2   27      0
885       1   19      0
886       3   29      2
887       1   26      0
888       3   32      0

[889 rows x 3 columns]

In [411]:
y

0      0
1      1
2      1
3      1
4      0
      ..
884    0
885    1
886    0
887    1
888    0
Name: survived, Length: 889, dtype: int64

In [412]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [413]:
model= LogisticRegression()

In [414]:
model.fit(X_train,y_train)

LogisticRegression()

In [415]:
model.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1], dtype=int64)

In [416]:
y_test

282    1
80     0
498    0
880    0
478    1
      ..
180    0
703    0
887    1
446    1
789    0
Name: survived, Length: 267, dtype: int64

In [417]:
model.score(X_test,y_test)

0.704119850187266

**StandardScaler:**

In [418]:
sc= StandardScaler()

In [419]:
sc.fit(X_train)

StandardScaler()

In [420]:
X_train_sc =sc.transform(X_train)
X_test_sc =sc.transform(X_test)

In [421]:
X_train_sc

array([[ 0.83963148, -0.04689258, -0.46386459],
       [ 0.83963148,  0.26505594, -0.46386459],
       [ 0.83963148, -0.20286684,  0.71378348],
       ...,
       [ 0.83963148, -0.04689258, -0.46386459],
       [ 0.83963148, -1.52864804,  1.89143155],
       [-0.36649042,  1.74681139, -0.46386459]])

**MinMaxScaler (Normalization):**

In [422]:
mms= MinMaxScaler()

In [423]:
mms.fit(X_train)

MinMaxScaler()

In [424]:
X_train_mms= mms.transform(X_train)
X_test_mms= mms.transform(X_test)


In [425]:
X_train_mms

array([[1.        , 0.3625    , 0.        ],
       [1.        , 0.4125    , 0.        ],
       [1.        , 0.3375    , 0.16666667],
       ...,
       [1.        , 0.3625    , 0.        ],
       [1.        , 0.125     , 0.33333333],
       [0.5       , 0.65      , 0.        ]])