In [76]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,roc_auc_score,f1_score, classification_report

**For Classification Task:**

In [77]:
# Generate a synthetic dataset
np.random.seed(42)
num_samples = 1000
X1 = np.random.rand(num_samples)
X2 = np.random.rand(num_samples)
y = (2*X1 + X2 > 1.5).astype(int)  # Target variable: 0 or 1

# Create a DataFrame to store the dataset
data = pd.DataFrame({'X1': X1, 'X2': X2, 'Target': y})

# Split the data into training and test sets
X = data.drop('Target', axis=1)
y = data['Target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Display the first few rows of the dataset
print(data.head())


         X1        X2  Target
0  0.374540  0.185133       0
1  0.950714  0.541901       1
2  0.731994  0.872946       1
3  0.598658  0.732225       1
4  0.156019  0.806561       0


In [78]:
data.shape

(1000, 3)

In [79]:
model= LogisticRegression()

In [80]:
model.fit(X_train,y_train)

LogisticRegression()

In [81]:
Prediction= model.predict(X_test)

In [82]:
Prediction

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0])

In [83]:
y_test= np.array(y_test)
y_test

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0])

In [84]:
model.score(X_test,y_test)

0.99

In [85]:
cm= confusion_matrix(y_true= y_test, y_pred= Prediction )

In [86]:
print(cm)

[[ 98   0]
 [  2 100]]


In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

# List of classifiers
classifiers = [
    LogisticRegression(max_iter=1000),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    SVC(),
    KNeighborsClassifier(),
    GaussianNB(),
    MLPClassifier(),
]

# Dictionary to store the results
results = {}

# Loop through each classifier and calculate metrics
for clf in classifiers:
    clf_name = clf.__class__.__name__
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='micro')
    recall = recall_score(y_test, y_pred, average='micro')
    f1 = f1_score(y_test, y_pred, average='micro')
 
    
    results[clf_name] = {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    }

# Print the results
for clf_name, metrics in results.items():
    print(f"{clf_name} Metrics:")
    for metric_name, value in metrics.items():
        print(f"{metric_name}: {value:.4f}")
    print("\n")

LogisticRegression Metrics:
Accuracy: 0.9800
Precision: 0.9800
Recall: 0.9800
F1 Score: 0.9800


DecisionTreeClassifier Metrics:
Accuracy: 0.9720
Precision: 0.9720
Recall: 0.9720
F1 Score: 0.9720


RandomForestClassifier Metrics:
Accuracy: 0.9820
Precision: 0.9820
Recall: 0.9820
F1 Score: 0.9820


SVC Metrics:
Accuracy: 0.9780
Precision: 0.9780
Recall: 0.9780
F1 Score: 0.9780


KNeighborsClassifier Metrics:
Accuracy: 0.9840
Precision: 0.9840
Recall: 0.9840
F1 Score: 0.9840


GaussianNB Metrics:
Accuracy: 0.9040
Precision: 0.9040
Recall: 0.9040
F1 Score: 0.9040


MLPClassifier Metrics:
Accuracy: 0.9900
Precision: 0.9900
Recall: 0.9900
F1 Score: 0.9900




c:\Users\shory\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


**For Regression Task:**

In [88]:

# Set a random seed for reproducibility
np.random.seed(42)

# Generate random data points for X (independent variable)
X = np.random.rand(100, 1)  # 100 data points in a column vector

# Generate corresponding values for y (dependent variable) with some noise
y = 3 * X + 2 + np.random.randn(100, 1)

# Now you have your dataset with X and y, representing a simple linear relationship


In [89]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size= 0.2)

In [90]:
model= LinearRegression()

In [91]:
model.fit(X_train,y_train)

LinearRegression()

In [92]:
Prediction=model.predict(X_test)

In [93]:
y_test

array([[3.63378632],
       [2.84722866],
       [6.45508479],
       [2.35294818],
       [4.2877426 ],
       [2.45438765],
       [1.27569043],
       [1.95826529],
       [3.8294257 ],
       [3.91821756],
       [2.33140293],
       [3.75910074],
       [4.5912248 ],
       [5.34741411],
       [4.75625845],
       [4.74501899],
       [2.24838403],
       [2.9771556 ],
       [5.74248368],
       [4.3437273 ]])

In [94]:
model.score(X_test,y_test)

0.3461837802973725

In [95]:
MAE= mean_absolute_error(y_test,Prediction)
MSE= mean_squared_error(y_test,Prediction)
RMSE= np.sqrt (MSE)
R2_score= r2_score(y_test,Prediction)

In [96]:
print("MAE:", MAE)
print("MSE:", MSE)
print("RMSE:", RMSE)
print("R2 score:", R2_score)

MAE: 0.8400059369426088
MSE: 1.170861925219628
RMSE: 1.082063734361164
R2 score: 0.3461837802973725
